"""
Expert (LoRA block) definitions used by the FedMoE simulation.
"""

from __future__ import annotations

import numpy as np


class ExpertModel:
    """
    Represents a LoRA expert (a lightweight adapter on top of a base Qwen model).
    """

    def __init__(self, name: str, model_dim: int, lora_rank: int) -> None:
        self.name = name
        self.version = 0
        self.lora_A = np.zeros((model_dim, lora_rank))
        self.lora_B = np.zeros((lora_rank, model_dim))
        print(f"[Coordinator] Registered Expert: {self.name}")

    def simulate_inference(self, prompt_part: str) -> str:
        """
        Produce a deterministic code stub that reflects the expert's contribution.
        """
        weight_norm = np.linalg.norm(self.lora_A)
        return (
            f"\n--- [Code from {self.name.upper()} (v{self.version}, norm={weight_norm:.2f})] ---\n"
            f"def generated_for_{self.name.lower()}(prompt='{prompt_part[:30]}...'):\n"
            f"    # Logic generated by this expert\n"
            f"    pass\n"
            f"--- [End of {self.name.upper()}] ---\n"
        )

